<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ANGRPUP" failures="3" tests="50" name="testng.CalculadoraDP" time="26.998" errors="0" timestamp="2025-04-16T20:36:18 BOT" skipped="0">
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.505"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.454"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.470"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.538"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.476"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.462"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.565"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.662"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.473"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.480"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.451"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.596">
    <failure message="expected [15.2] but found [15.200000000000001]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [15.2] but found [15.200000000000001]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testng.CalculadoraDP.mainTest(CalculadoraDP.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- mainTest -->
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.844"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.682">
    <failure message="expected [-6.1] but found [-6.1000000000000005]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [-6.1] but found [-6.1000000000000005]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testng.CalculadoraDP.mainTest(CalculadoraDP.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- mainTest -->
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.475">
    <failure message="expected [10.8] but found [10.799999999999999]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [10.8] but found [10.799999999999999]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testng.CalculadoraDP.mainTest(CalculadoraDP.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- mainTest -->
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.543"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.627"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.422"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.482"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.623"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.856"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.455"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.646"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.784"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.417"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.699"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.470"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.572"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.471"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.492"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.617"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.585"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.444"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.464"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.456"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.599"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.501"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.523"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.525"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.530"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.460"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.569"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.477"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.418"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.478"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.632"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.537"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.462"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.476"/>
  <testcase classname="testng.CalculadoraDP" name="mainTest" time="0.553"/>
</testsuite> <!-- testng.CalculadoraDP -->
